//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cust_payout")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub user_id: i64,
    pub pid: i64,
    pub cid: i64,
    pub alias: String,
    pub chain_id: String,
    pub token_id: String,
    pub address: String,
    #[sea_orm(column_type = "Decimal(Some((12, 6)))")]
    pub amount: Decimal,
    pub status: i64,
    pub txid: String,
    pub block_height: String,
    pub block_time: DateTime,
    pub nonce: String,
    pub times: DateTime,
    pub sign: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
