//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cust_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub username: String,
    pub password: String,
    pub nickname: String,
    pub email: String,
    pub avatar: Option<String>,
    pub status: i16,
    pub login_ip: Option<String>,
    pub login_data: Option<DateTime>,
    pub creator: Option<String>,
    pub creator_time: DateTime,
    pub update: Option<String>,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
