//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cust_operate_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub log_level: String,
    pub trace_id: Option<String>,
    pub user_id: i64,
    pub operate: String,
    pub action: String,
    pub extra: String,
    pub result: String,
    pub req_method: Option<String>,
    pub req_url: Option<String>,
    pub user_ip: Option<String>,
    pub user_agent: Option<String>,
    pub res_code: Option<String>,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
